// source: ConversationMessages.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var MessageBody_pb = require('./MessageBody_pb.js');
goog.object.extend(proto, MessageBody_pb);
var ConversationInfoV2_pb = require('./ConversationInfoV2_pb.js');
goog.object.extend(proto, ConversationInfoV2_pb);
goog.exportSymbol('proto.douyin.ConversationMessage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.douyin.ConversationMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.douyin.ConversationMessage.repeatedFields_, null);
};
goog.inherits(proto.douyin.ConversationMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.douyin.ConversationMessage.displayName = 'proto.douyin.ConversationMessage';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.douyin.ConversationMessage.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.douyin.ConversationMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.douyin.ConversationMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.douyin.ConversationMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.ConversationMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    conversations: (f = msg.getConversations()) && ConversationInfoV2_pb.ConversationInfoV2.toObject(includeInstance, f),
    messagesList: jspb.Message.toObjectList(msg.getMessagesList(),
    MessageBody_pb.MessageBody.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.douyin.ConversationMessage}
 */
proto.douyin.ConversationMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.douyin.ConversationMessage;
  return proto.douyin.ConversationMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.douyin.ConversationMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.douyin.ConversationMessage}
 */
proto.douyin.ConversationMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new ConversationInfoV2_pb.ConversationInfoV2;
      reader.readMessage(value,ConversationInfoV2_pb.ConversationInfoV2.deserializeBinaryFromReader);
      msg.setConversations(value);
      break;
    case 2:
      var value = new MessageBody_pb.MessageBody;
      reader.readMessage(value,MessageBody_pb.MessageBody.deserializeBinaryFromReader);
      msg.addMessages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.douyin.ConversationMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.douyin.ConversationMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.douyin.ConversationMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.ConversationMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConversations();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      ConversationInfoV2_pb.ConversationInfoV2.serializeBinaryToWriter
    );
  }
  f = message.getMessagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      MessageBody_pb.MessageBody.serializeBinaryToWriter
    );
  }
};


/**
 * optional ConversationInfoV2 conversations = 1;
 * @return {?proto.douyin.ConversationInfoV2}
 */
proto.douyin.ConversationMessage.prototype.getConversations = function() {
  return /** @type{?proto.douyin.ConversationInfoV2} */ (
    jspb.Message.getWrapperField(this, ConversationInfoV2_pb.ConversationInfoV2, 1));
};


/**
 * @param {?proto.douyin.ConversationInfoV2|undefined} value
 * @return {!proto.douyin.ConversationMessage} returns this
*/
proto.douyin.ConversationMessage.prototype.setConversations = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.douyin.ConversationMessage} returns this
 */
proto.douyin.ConversationMessage.prototype.clearConversations = function() {
  return this.setConversations(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.douyin.ConversationMessage.prototype.hasConversations = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated MessageBody messages = 2;
 * @return {!Array<!proto.douyin.MessageBody>}
 */
proto.douyin.ConversationMessage.prototype.getMessagesList = function() {
  return /** @type{!Array<!proto.douyin.MessageBody>} */ (
    jspb.Message.getRepeatedWrapperField(this, MessageBody_pb.MessageBody, 2));
};


/**
 * @param {!Array<!proto.douyin.MessageBody>} value
 * @return {!proto.douyin.ConversationMessage} returns this
*/
proto.douyin.ConversationMessage.prototype.setMessagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.douyin.MessageBody=} opt_value
 * @param {number=} opt_index
 * @return {!proto.douyin.MessageBody}
 */
proto.douyin.ConversationMessage.prototype.addMessages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.douyin.MessageBody, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.douyin.ConversationMessage} returns this
 */
proto.douyin.ConversationMessage.prototype.clearMessagesList = function() {
  return this.setMessagesList([]);
};


goog.object.extend(exports, proto.douyin);
