// source: CreateConversationV2ResponseBody.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var ConversationInfoV2_pb = require('./ConversationInfoV2_pb.js');
goog.object.extend(proto, ConversationInfoV2_pb);
goog.exportSymbol('proto.douyin.CreateConversationV2ResponseBody', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.douyin.CreateConversationV2ResponseBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.douyin.CreateConversationV2ResponseBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.douyin.CreateConversationV2ResponseBody.displayName = 'proto.douyin.CreateConversationV2ResponseBody';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.toObject = function(opt_includeInstance) {
  return proto.douyin.CreateConversationV2ResponseBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.douyin.CreateConversationV2ResponseBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.CreateConversationV2ResponseBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    conversation: (f = msg.getConversation()) && ConversationInfoV2_pb.ConversationInfoV2.toObject(includeInstance, f),
    checkCode: jspb.Message.getFieldWithDefault(msg, 2, 0),
    checkMessage: jspb.Message.getFieldWithDefault(msg, 3, ""),
    extraInfo: jspb.Message.getFieldWithDefault(msg, 4, ""),
    status: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.douyin.CreateConversationV2ResponseBody}
 */
proto.douyin.CreateConversationV2ResponseBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.douyin.CreateConversationV2ResponseBody;
  return proto.douyin.CreateConversationV2ResponseBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.douyin.CreateConversationV2ResponseBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.douyin.CreateConversationV2ResponseBody}
 */
proto.douyin.CreateConversationV2ResponseBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new ConversationInfoV2_pb.ConversationInfoV2;
      reader.readMessage(value,ConversationInfoV2_pb.ConversationInfoV2.deserializeBinaryFromReader);
      msg.setConversation(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCheckCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCheckMessage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtraInfo(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.douyin.CreateConversationV2ResponseBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.douyin.CreateConversationV2ResponseBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.CreateConversationV2ResponseBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConversation();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      ConversationInfoV2_pb.ConversationInfoV2.serializeBinaryToWriter
    );
  }
  f = message.getCheckCode();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getCheckMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getExtraInfo();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional ConversationInfoV2 conversation = 1;
 * @return {?proto.douyin.ConversationInfoV2}
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.getConversation = function() {
  return /** @type{?proto.douyin.ConversationInfoV2} */ (
    jspb.Message.getWrapperField(this, ConversationInfoV2_pb.ConversationInfoV2, 1));
};


/**
 * @param {?proto.douyin.ConversationInfoV2|undefined} value
 * @return {!proto.douyin.CreateConversationV2ResponseBody} returns this
*/
proto.douyin.CreateConversationV2ResponseBody.prototype.setConversation = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.douyin.CreateConversationV2ResponseBody} returns this
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.clearConversation = function() {
  return this.setConversation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.hasConversation = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 check_code = 2;
 * @return {number}
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.getCheckCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.CreateConversationV2ResponseBody} returns this
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.setCheckCode = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string check_message = 3;
 * @return {string}
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.getCheckMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.douyin.CreateConversationV2ResponseBody} returns this
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.setCheckMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string extra_info = 4;
 * @return {string}
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.getExtraInfo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.douyin.CreateConversationV2ResponseBody} returns this
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.setExtraInfo = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 status = 5;
 * @return {number}
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.getStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.CreateConversationV2ResponseBody} returns this
 */
proto.douyin.CreateConversationV2ResponseBody.prototype.setStatus = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


goog.object.extend(exports, proto.douyin);
