// source: MessageBody.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.douyin.MessageBody', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.douyin.MessageBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.douyin.MessageBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.douyin.MessageBody.displayName = 'proto.douyin.MessageBody';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.douyin.MessageBody.prototype.toObject = function(opt_includeInstance) {
  return proto.douyin.MessageBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.douyin.MessageBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.MessageBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    conversationId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    conversationType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    serverMessageId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    indexInConversation: jspb.Message.getFieldWithDefault(msg, 4, 0),
    conversationShortId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    messageType: jspb.Message.getFieldWithDefault(msg, 6, 0),
    sender: jspb.Message.getFieldWithDefault(msg, 7, 0),
    content: jspb.Message.getFieldWithDefault(msg, 8, ""),
    extMap: (f = msg.getExtMap()) ? f.toObject(includeInstance, undefined) : [],
    createTime: jspb.Message.getFieldWithDefault(msg, 10, 0),
    version: jspb.Message.getFieldWithDefault(msg, 11, 0),
    status: jspb.Message.getFieldWithDefault(msg, 12, 0),
    orderInConversation: jspb.Message.getFieldWithDefault(msg, 13, 0),
    secSender: jspb.Message.getFieldWithDefault(msg, 14, ""),
    indexInConversationV2: jspb.Message.getFieldWithDefault(msg, 17, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.douyin.MessageBody}
 */
proto.douyin.MessageBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.douyin.MessageBody;
  return proto.douyin.MessageBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.douyin.MessageBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.douyin.MessageBody}
 */
proto.douyin.MessageBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setConversationId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setConversationType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setServerMessageId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIndexInConversation(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setConversationShortId(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMessageType(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSender(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 9:
      var value = msg.getExtMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreateTime(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setVersion(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatus(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOrderInConversation(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecSender(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIndexInConversationV2(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.douyin.MessageBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.douyin.MessageBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.douyin.MessageBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.MessageBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConversationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConversationType();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getServerMessageId();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getIndexInConversation();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getConversationShortId();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getMessageType();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getSender();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getExtMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(9, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getCreateTime();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getOrderInConversation();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = message.getSecSender();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getIndexInConversationV2();
  if (f !== 0) {
    writer.writeInt64(
      17,
      f
    );
  }
};


/**
 * optional string conversation_id = 1;
 * @return {string}
 */
proto.douyin.MessageBody.prototype.getConversationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setConversationId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 conversation_type = 2;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getConversationType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setConversationType = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 server_message_id = 3;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getServerMessageId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setServerMessageId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 index_in_conversation = 4;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getIndexInConversation = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setIndexInConversation = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 conversation_short_id = 5;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getConversationShortId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setConversationShortId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 message_type = 6;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getMessageType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setMessageType = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 sender = 7;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getSender = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setSender = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string content = 8;
 * @return {string}
 */
proto.douyin.MessageBody.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * map<string, string> ext = 9;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.douyin.MessageBody.prototype.getExtMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 9, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.clearExtMap = function() {
  this.getExtMap().clear();
  return this;};


/**
 * optional int64 create_time = 10;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getCreateTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setCreateTime = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int64 version = 11;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 status = 12;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setStatus = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int64 order_in_conversation = 13;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getOrderInConversation = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setOrderInConversation = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional string sec_sender = 14;
 * @return {string}
 */
proto.douyin.MessageBody.prototype.getSecSender = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setSecSender = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional int64 index_in_conversation_v2 = 17;
 * @return {number}
 */
proto.douyin.MessageBody.prototype.getIndexInConversationV2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageBody} returns this
 */
proto.douyin.MessageBody.prototype.setIndexInConversationV2 = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


goog.object.extend(exports, proto.douyin);
