// source: MessageByInitResponseBody.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var ConversationMessages_pb = require('./ConversationMessages_pb.js');
goog.object.extend(proto, ConversationMessages_pb);
goog.exportSymbol('proto.douyin.MessageByInitResponseBody', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.douyin.MessageByInitResponseBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.douyin.MessageByInitResponseBody.repeatedFields_, null);
};
goog.inherits(proto.douyin.MessageByInitResponseBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.douyin.MessageByInitResponseBody.displayName = 'proto.douyin.MessageByInitResponseBody';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.douyin.MessageByInitResponseBody.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.douyin.MessageByInitResponseBody.prototype.toObject = function(opt_includeInstance) {
  return proto.douyin.MessageByInitResponseBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.douyin.MessageByInitResponseBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.MessageByInitResponseBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    messagesList: jspb.Message.toObjectList(msg.getMessagesList(),
    ConversationMessages_pb.ConversationMessage.toObject, includeInstance),
    hasMore: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    nextInitVersion: jspb.Message.getFieldWithDefault(msg, 3, 0),
    version: jspb.Message.getFieldWithDefault(msg, 4, 0),
    userCursor: jspb.Message.getFieldWithDefault(msg, 5, 0),
    cmdIndex: jspb.Message.getFieldWithDefault(msg, 6, 0),
    readconvVersion: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.douyin.MessageByInitResponseBody}
 */
proto.douyin.MessageByInitResponseBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.douyin.MessageByInitResponseBody;
  return proto.douyin.MessageByInitResponseBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.douyin.MessageByInitResponseBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.douyin.MessageByInitResponseBody}
 */
proto.douyin.MessageByInitResponseBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new ConversationMessages_pb.ConversationMessage;
      reader.readMessage(value,ConversationMessages_pb.ConversationMessage.deserializeBinaryFromReader);
      msg.addMessages(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasMore(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNextInitVersion(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setVersion(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserCursor(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCmdIndex(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setReadconvVersion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.douyin.MessageByInitResponseBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.douyin.MessageByInitResponseBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.douyin.MessageByInitResponseBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.MessageByInitResponseBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      ConversationMessages_pb.ConversationMessage.serializeBinaryToWriter
    );
  }
  f = message.getHasMore();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getNextInitVersion();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getUserCursor();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getCmdIndex();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getReadconvVersion();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
};


/**
 * repeated ConversationMessage messages = 1;
 * @return {!Array<!proto.douyin.ConversationMessage>}
 */
proto.douyin.MessageByInitResponseBody.prototype.getMessagesList = function() {
  return /** @type{!Array<!proto.douyin.ConversationMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, ConversationMessages_pb.ConversationMessage, 1));
};


/**
 * @param {!Array<!proto.douyin.ConversationMessage>} value
 * @return {!proto.douyin.MessageByInitResponseBody} returns this
*/
proto.douyin.MessageByInitResponseBody.prototype.setMessagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.douyin.ConversationMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.douyin.ConversationMessage}
 */
proto.douyin.MessageByInitResponseBody.prototype.addMessages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.douyin.ConversationMessage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.douyin.MessageByInitResponseBody} returns this
 */
proto.douyin.MessageByInitResponseBody.prototype.clearMessagesList = function() {
  return this.setMessagesList([]);
};


/**
 * optional bool has_more = 2;
 * @return {boolean}
 */
proto.douyin.MessageByInitResponseBody.prototype.getHasMore = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.douyin.MessageByInitResponseBody} returns this
 */
proto.douyin.MessageByInitResponseBody.prototype.setHasMore = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional int64 next_init_version = 3;
 * @return {number}
 */
proto.douyin.MessageByInitResponseBody.prototype.getNextInitVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageByInitResponseBody} returns this
 */
proto.douyin.MessageByInitResponseBody.prototype.setNextInitVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 version = 4;
 * @return {number}
 */
proto.douyin.MessageByInitResponseBody.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageByInitResponseBody} returns this
 */
proto.douyin.MessageByInitResponseBody.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 user_cursor = 5;
 * @return {number}
 */
proto.douyin.MessageByInitResponseBody.prototype.getUserCursor = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageByInitResponseBody} returns this
 */
proto.douyin.MessageByInitResponseBody.prototype.setUserCursor = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 cmd_index = 6;
 * @return {number}
 */
proto.douyin.MessageByInitResponseBody.prototype.getCmdIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageByInitResponseBody} returns this
 */
proto.douyin.MessageByInitResponseBody.prototype.setCmdIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 readconv_version = 7;
 * @return {number}
 */
proto.douyin.MessageByInitResponseBody.prototype.getReadconvVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessageByInitResponseBody} returns this
 */
proto.douyin.MessageByInitResponseBody.prototype.setReadconvVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


goog.object.extend(exports, proto.douyin);
