// source: MessagePerUserResponseBody.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var MessageBody_pb = require('./MessageBody_pb.js');
goog.object.extend(proto, MessageBody_pb);
goog.exportSymbol('proto.douyin.MessagePerUserResponseBody', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.douyin.MessagePerUserResponseBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.douyin.MessagePerUserResponseBody.repeatedFields_, null);
};
goog.inherits(proto.douyin.MessagePerUserResponseBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.douyin.MessagePerUserResponseBody.displayName = 'proto.douyin.MessagePerUserResponseBody';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.douyin.MessagePerUserResponseBody.repeatedFields_ = [1,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.douyin.MessagePerUserResponseBody.prototype.toObject = function(opt_includeInstance) {
  return proto.douyin.MessagePerUserResponseBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.douyin.MessagePerUserResponseBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.MessagePerUserResponseBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    messagesList: jspb.Message.toObjectList(msg.getMessagesList(),
    MessageBody_pb.MessageBody.toObject, includeInstance),
    nextCursor: jspb.Message.getFieldWithDefault(msg, 2, 0),
    hasMore: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    nextInterval: jspb.Message.getFieldWithDefault(msg, 4, 0),
    nextConversationVersion: jspb.Message.getFieldWithDefault(msg, 5, 0),
    nextCmdIndex: jspb.Message.getFieldWithDefault(msg, 7, 0),
    hasmoreMessageConvListList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.douyin.MessagePerUserResponseBody}
 */
proto.douyin.MessagePerUserResponseBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.douyin.MessagePerUserResponseBody;
  return proto.douyin.MessagePerUserResponseBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.douyin.MessagePerUserResponseBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.douyin.MessagePerUserResponseBody}
 */
proto.douyin.MessagePerUserResponseBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new MessageBody_pb.MessageBody;
      reader.readMessage(value,MessageBody_pb.MessageBody.deserializeBinaryFromReader);
      msg.addMessages(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNextCursor(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasMore(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNextInterval(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNextConversationVersion(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNextCmdIndex(value);
      break;
    case 8:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addHasmoreMessageConvList(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.douyin.MessagePerUserResponseBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.douyin.MessagePerUserResponseBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.douyin.MessagePerUserResponseBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.MessagePerUserResponseBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      MessageBody_pb.MessageBody.serializeBinaryToWriter
    );
  }
  f = message.getNextCursor();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getHasMore();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getNextInterval();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getNextConversationVersion();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getNextCmdIndex();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getHasmoreMessageConvListList();
  if (f.length > 0) {
    writer.writePackedInt64(
      8,
      f
    );
  }
};


/**
 * repeated MessageBody messages = 1;
 * @return {!Array<!proto.douyin.MessageBody>}
 */
proto.douyin.MessagePerUserResponseBody.prototype.getMessagesList = function() {
  return /** @type{!Array<!proto.douyin.MessageBody>} */ (
    jspb.Message.getRepeatedWrapperField(this, MessageBody_pb.MessageBody, 1));
};


/**
 * @param {!Array<!proto.douyin.MessageBody>} value
 * @return {!proto.douyin.MessagePerUserResponseBody} returns this
*/
proto.douyin.MessagePerUserResponseBody.prototype.setMessagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.douyin.MessageBody=} opt_value
 * @param {number=} opt_index
 * @return {!proto.douyin.MessageBody}
 */
proto.douyin.MessagePerUserResponseBody.prototype.addMessages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.douyin.MessageBody, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.douyin.MessagePerUserResponseBody} returns this
 */
proto.douyin.MessagePerUserResponseBody.prototype.clearMessagesList = function() {
  return this.setMessagesList([]);
};


/**
 * optional int64 next_cursor = 2;
 * @return {number}
 */
proto.douyin.MessagePerUserResponseBody.prototype.getNextCursor = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessagePerUserResponseBody} returns this
 */
proto.douyin.MessagePerUserResponseBody.prototype.setNextCursor = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional bool has_more = 3;
 * @return {boolean}
 */
proto.douyin.MessagePerUserResponseBody.prototype.getHasMore = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.douyin.MessagePerUserResponseBody} returns this
 */
proto.douyin.MessagePerUserResponseBody.prototype.setHasMore = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional int64 next_interval = 4;
 * @return {number}
 */
proto.douyin.MessagePerUserResponseBody.prototype.getNextInterval = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessagePerUserResponseBody} returns this
 */
proto.douyin.MessagePerUserResponseBody.prototype.setNextInterval = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 next_conversation_version = 5;
 * @return {number}
 */
proto.douyin.MessagePerUserResponseBody.prototype.getNextConversationVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessagePerUserResponseBody} returns this
 */
proto.douyin.MessagePerUserResponseBody.prototype.setNextConversationVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 next_cmd_index = 7;
 * @return {number}
 */
proto.douyin.MessagePerUserResponseBody.prototype.getNextCmdIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.MessagePerUserResponseBody} returns this
 */
proto.douyin.MessagePerUserResponseBody.prototype.setNextCmdIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * repeated int64 hasmore_message_conv_list = 8;
 * @return {!Array<number>}
 */
proto.douyin.MessagePerUserResponseBody.prototype.getHasmoreMessageConvListList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.douyin.MessagePerUserResponseBody} returns this
 */
proto.douyin.MessagePerUserResponseBody.prototype.setHasmoreMessageConvListList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.douyin.MessagePerUserResponseBody} returns this
 */
proto.douyin.MessagePerUserResponseBody.prototype.addHasmoreMessageConvList = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.douyin.MessagePerUserResponseBody} returns this
 */
proto.douyin.MessagePerUserResponseBody.prototype.clearHasmoreMessageConvListList = function() {
  return this.setHasmoreMessageConvListList([]);
};


goog.object.extend(exports, proto.douyin);
