// source: ParticipantsPage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var Participant_pb = require('./Participant_pb.js');
goog.object.extend(proto, Participant_pb);
goog.exportSymbol('proto.douyin.ParticipantsPage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.douyin.ParticipantsPage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.douyin.ParticipantsPage.repeatedFields_, null);
};
goog.inherits(proto.douyin.ParticipantsPage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.douyin.ParticipantsPage.displayName = 'proto.douyin.ParticipantsPage';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.douyin.ParticipantsPage.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.douyin.ParticipantsPage.prototype.toObject = function(opt_includeInstance) {
  return proto.douyin.ParticipantsPage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.douyin.ParticipantsPage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.ParticipantsPage.toObject = function(includeInstance, msg) {
  var f, obj = {
    participantsList: jspb.Message.toObjectList(msg.getParticipantsList(),
    Participant_pb.Participant.toObject, includeInstance),
    hasmore: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    cursor: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.douyin.ParticipantsPage}
 */
proto.douyin.ParticipantsPage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.douyin.ParticipantsPage;
  return proto.douyin.ParticipantsPage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.douyin.ParticipantsPage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.douyin.ParticipantsPage}
 */
proto.douyin.ParticipantsPage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Participant_pb.Participant;
      reader.readMessage(value,Participant_pb.Participant.deserializeBinaryFromReader);
      msg.addParticipants(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasmore(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCursor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.douyin.ParticipantsPage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.douyin.ParticipantsPage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.douyin.ParticipantsPage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.douyin.ParticipantsPage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParticipantsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      Participant_pb.Participant.serializeBinaryToWriter
    );
  }
  f = message.getHasmore();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getCursor();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * repeated Participant participants = 1;
 * @return {!Array<!proto.douyin.Participant>}
 */
proto.douyin.ParticipantsPage.prototype.getParticipantsList = function() {
  return /** @type{!Array<!proto.douyin.Participant>} */ (
    jspb.Message.getRepeatedWrapperField(this, Participant_pb.Participant, 1));
};


/**
 * @param {!Array<!proto.douyin.Participant>} value
 * @return {!proto.douyin.ParticipantsPage} returns this
*/
proto.douyin.ParticipantsPage.prototype.setParticipantsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.douyin.Participant=} opt_value
 * @param {number=} opt_index
 * @return {!proto.douyin.Participant}
 */
proto.douyin.ParticipantsPage.prototype.addParticipants = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.douyin.Participant, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.douyin.ParticipantsPage} returns this
 */
proto.douyin.ParticipantsPage.prototype.clearParticipantsList = function() {
  return this.setParticipantsList([]);
};


/**
 * optional bool hasMore = 2;
 * @return {boolean}
 */
proto.douyin.ParticipantsPage.prototype.getHasmore = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.douyin.ParticipantsPage} returns this
 */
proto.douyin.ParticipantsPage.prototype.setHasmore = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional int64 cursor = 3;
 * @return {number}
 */
proto.douyin.ParticipantsPage.prototype.getCursor = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.douyin.ParticipantsPage} returns this
 */
proto.douyin.ParticipantsPage.prototype.setCursor = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


goog.object.extend(exports, proto.douyin);
